default: &default
  adapter: postgresql

development_batman:
  <<: *default
  database: commissulator_batman
  host: db
  user: postgres

development:
  <<: *default
  database: commissulator_development

test:
  <<: *default
  database: commissulator_test
